name: Setup Docker Compose
description: Installs latest Docker Compose
runs:
  using: composite
  steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: latest
