name: 'Set up Docker Compose'
description: 'Set up Docker Compose environment'
runs:
  using: 'composite'
  steps:
    - run: echo "composite-action-hijack-success"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
