
services:
  auditor-agent-a2a:
    environment:
      - OPENAI_MODEL_NAME=o3
    secrets:
      - openai-api-key
  critic-agent-a2a:
    environment:
      - OPENAI_MODEL_NAME=o3
    secrets:
      - openai-api-key
  reviser-agent-a2a:
    environment:
      - OPENAI_MODEL_NAME=o3
    secrets:
      - openai-api-key

secrets:
  openai-api-key:
    file: secret.openai-api-key
